import tkinter as tk

class EntryFrame(tk.Frame):
    def __init__(self, parent, auth_view):
        super().__init__(parent, bg="gray82")
        self.auth_view = auth_view

        self.username_entry = tk.Entry(self)
        self.username_entry.place(relx=0.367, rely=0.1, height=20, relwidth=0.613)
        self.username_entry.configure(background="gray82")
        self.username_entry.configure(disabledforeground="#9d9d9d")
        self.username_entry.configure(font="TkFixedFont")
        self.username_entry.configure(foreground="black")
        self.username_entry.configure(highlightbackground="gray82")
        self.username_entry.configure(highlightcolor="black")
        self.username_entry.configure(insertbackground="black")
        self.username_entry.configure(selectbackground="#d9d9d9")
        self.username_entry.configure(selectforeground="black")

        self.password_entry = tk.Entry(self)
        self.password_entry.place(relx=0.367, rely=0.3, height=20, relwidth=0.613)
        self.password_entry.configure(background="gray82")
        self.password_entry.configure(disabledforeground="#9d9d9d")
        self.password_entry.configure(font="TkFixedFont")
        self.password_entry.configure(foreground="black")
        self.password_entry.configure(highlightbackground="gray82")
        self.password_entry.configure(highlightcolor="black")
        self.password_entry.configure(insertbackground="black")
        self.password_entry.configure(selectbackground="#d9d9d9")
        self.password_entry.configure(selectforeground="black")

        self.confirm_password_entry = tk.Entry(self)
        self.confirm_password_entry.place(relx=0.367, rely=0.5, height=20, relwidth=0.613)
        self.confirm_password_entry.configure(background="gray82")
        self.confirm_password_entry.configure(disabledforeground="#9d9d9d")
        self.confirm_password_entry.configure(font="TkFixedFont")
        self.confirm_password_entry.configure(foreground="black")
        self.confirm_password_entry.configure(highlightbackground="gray82")
        self.confirm_password_entry.configure(highlightcolor="black")
        self.confirm_password_entry.configure(insertbackground="black")
        self.confirm_password_entry.configure(selectbackground="#d9d9d9")
        self.confirm_password_entry.configure(selectforeground="black")

        self.username_label = tk.Label(self, text="tài khoản", bg="gray82")
        self.username_label.place(relx=0.017, rely=0.1, height=20, width=57)
        self.username_label.configure(activebackground="#d9d9d9")
        self.username_label.configure(activeforeground="black")
        self.username_label.configure(anchor='w')
        self.username_label.configure(compound='left')
        self.username_label.configure(disabledforeground="#9d9d9d")
        self.username_label.configure(foreground="black")
        self.username_label.configure(highlightbackground="gray82")
        self.username_label.configure(highlightcolor="black")

        self.password_label = tk.Label(self, text="Mật khẩu", bg="gray82")
        self.password_label.place(relx=0.0, rely=0.3, height=20, width=62)
        self.password_label.configure(activebackground="#d9d9d9")
        self.password_label.configure(activeforeground="black")
        self.password_label.configure(anchor='w')
        self.password_label.configure(compound='left')
        self.password_label.configure(disabledforeground="#9d9d9d")
        self.password_label.configure(foreground="black")
        self.password_label.configure(highlightbackground="gray82")
        self.password_label.configure(highlightcolor="black")

        self.confirm_password_label = tk.Label(self, text="Nhập lại mật khẩu\n(Nếu đăng ký)", bg="gray82")
        self.confirm_password_label.place(relx=0.0, rely=0.5, height=34, width=107)
        self.confirm_password_label.configure(activebackground="#d9d9d9")
        self.confirm_password_label.configure(activeforeground="black")
        self.confirm_password_label.configure(anchor='w')
        self.confirm_password_label.configure(compound='left')
        self.confirm_password_label.configure(disabledforeground="#9d9d9d")
        self.confirm_password_label.configure(foreground="black")
        self.confirm_password_label.configure(highlightbackground="gray82")
        self.confirm_password_label.configure(highlightcolor="black")
